### ISSUE TITLE
Create package based on CES.jl structure

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#1]
- [x] We need to create this package with bors, etc (the same as used in CalibrateEmulateSample.jl)
- [x] We need a readme.md for the front page
- [x] We need to populate the Project toml with the packages from CalibrateEmulateSample.jl required (only) for EnsembleKalmanProcesses (This will not include the python dependencies)
- [x] We need to copy across the Loss Minimization and to copy-and-cut the optimization part of Lorenz 96/Cloudy examples.

**Comment by jakebolewski** [comment]
@odunbar code coverage should be enabled now

**Comment by jakebolewski** [comment]
Closed by #9
