### ISSUE TITLE
Deterministic behavior of stochastic functions should not be the default

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/EnsembleKalmanProcesses.jl#104]
A consequence of #95 is that now, some functions that should be stochastic by default are deterministic.

An example of this is the following,

```
using Distributions
using Random

using EnsembleKalmanProcesses
using EnsembleKalmanProcesses.ParameterDistributions

d = Parameterized(Normal(0, 1))
c = no_constraint()
name = "unconstrained_normal"
u = ParameterDistribution(d, c, name)

for i in 1:5
   println(construct_initial_ensemble(u, 1))
end
```

This outputs,

```
[0.7883556016042917;;]
[0.7883556016042917;;]
[0.7883556016042917;;]
[0.7883556016042917;;]
[0.7883556016042917;;]
```

which means that we are no longer sampling i.i.d from the distribution. This is desirable for reproducibility of tests, but **not** as the default behavior. The expected user behavior can be achieved at the moment using

```
for i in 1:5
       println(construct_initial_ensemble(u, 1, rng= Random.GLOBAL_RNG))
end
```

which for example can output

```
[0.9548452855545422;;]
[0.3785684038407532;;]
[-0.257360852691082;;]
[-1.1705533137462902;;]
[0.9307323496630826;;]
```

Proposed solution: Make Random.GLOBAL_RNG the default AbstractRNG kwarg for all functions in the package, pass rng when the user wants reproducibility (e.g., test suite)

**Comment by ilopezgp** [comment]
@tsj5 let me know if you have bandwidth to solve this issue

**Comment by tsj5** [comment]
@ilopezgp oof, that's a bad bug, didn't mean to break the rng entirely! Thanks for catching this -- was caused by not thinking through the consequences of default kwargs, as you pointed out. Will have a PR to fix it in a few min...
