### ISSUE TITLE
Add LearningRateSchedulers

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/EnsembleKalmanProcesses.jl#154]
Following typical optimizer structures in deep learning (tensor flow, pytorch), we can add the possibility of defining a `LearningRateScheduler` at construction time for EKP. 

Then, we would set the default dt based on the scheduler, and perhaps still expose this parameter for the user in case they want to try out some other schedule.

**Comment by eviatarbach** [comment]
This paper that @odunbar found could be a possible option: https://doi.org/10.1088/1361-6420/abd29b
