### ISSUE TITLE
Move `\Delta t`to be stored as a "Process" variable

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#16]
Unless we have a suitably general way of including timestepping into every EKP, then this object really should be a process variable of `Inversion` and `Sampler`, and not an `EnsembleKalmanProcess` variable 

@bielim co-authored

**Comment by ilopezgp** [comment]
I believe we always do have a way to include the time step? It comes from the discretization of the continuous form of the updates, and we can do the same for UKI, as shown in Huang et al, 2021.

**Comment by odunbar** [comment]
We create an array in all cases. It should be noted that in (Sparse) EKI and EKS have an array with `Delta t[current_step]` being the current `Delta t`. Currently i believe UKI has a single entry array `[Delta t]` that is not updated?

**Comment by ilopezgp** [comment]
@odunbar see #109 for a fix.
