### ISSUE TITLE
Unit test failure for inflation

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#170]
On a Mac, and Julia 1.6.6

line 522 of `test/EnsembleKalmanProcesses/runtests.jl`. 

Causes Domain-error with `eigmax`, (as well as the desired warning)

co-authored with @anagha548

**Comment by eviatarbach** [comment]
Which test is failing specifically? Line 522 in `test/EnsembleKalmanProcesses/runtests.jl` in the latest version is not related to localization, nor eigendecomposition.

**Comment by odunbar** [comment]
Oh my apologies @eviatarbach, it's for inflation not localization, perhaps @ilopezgp knows. The test is indeed
 https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/7dcaa5c7a8dcd01ada412db66d0850dcd3658a11/test/EnsembleKalmanProcess/runtests.jl#L522

This calls 

https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/7dcaa5c7a8dcd01ada412db66d0850dcd3658a11/src/EnsembleKalmanProcess.jl#L294-L310

The test is trying to get the warning for line 301, (which it does return) but then it also gives a `DomainError` in `eigmax` in line 304

**Comment by ilopezgp** [comment]
Based on the docs, I think the DomainError came from the floating point errors that made some of the eigenvalues complex. I will just cast it to Symmetric, since it is a covariance.
