### ISSUE TITLE
Clean up notation in the documentation

### ISSUE THREAD

**Issue by ilopezgp** [CliMA/EnsembleKalmanProcesses.jl#190]
Since the documentation of different parts of the package has been written by different people, different notation has been used to refer to the same terms/concepts in several entries of the docs (e.g., UKI and EKI pages).

To provide a cleaner and more consistent documentation, we should unify notation across the docs.

**Comment by odunbar** [comment]
@Zhengyu-Huang https://clima.github.io/EnsembleKalmanProcesses.jl/dev/unscented_kalman_inversion/
what is `kappa=0` supposed to mean on this page, it doesn't really make sense to me the way it is currently described.

**Comment by ilopezgp** [comment]
I think it was a free parameter in an earlier version of the paper, which was later removed from the published version; see eq. (18) and below in https://doi.org/10.1016/j.jcp.2022.111262. I would say let's delete `kappa` altogether, to have the docs resemble the paper.

**Comment by ilopezgp** [comment]
We also don't have `kappa` in `src/`, btw.
