### ISSUE TITLE
Using EKP with deterministic and non-deterministic models

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#23]
## Deterministic setup
For a deterministic forward map G, the current EKP implementation works on the mean `\bar{y}` and covariance `\Gamma` of the data. Internally a regularization technique in the form drawing new samples of data for each iteration and ensemble member.

Effectively this solves the problem `y = G(\theta) + N(0,\Gamma)` by generating samples of `\gamma_i ~ N(0,\Gamma)` and using samples `y_i = \bar{y} + \gamma_i` in the algorithm. As we provide `\bar{y}` we achieve an unbiased result.

Also note - There should be no issue in this formulation working where `\bar{y}` is replaced by a sample `y` (and the algorithm still perturbs this internally). In this case one will acheive a (naturally) sample-biased result. 

## Nondeterministic setup
For nondeterministic forward map G (with mean `\bar{G}`) we would like to use a sample `y` and covariance `\Gamma` here. We do not regularize (redraw the data at every iteration) because the internal variability is sufficient.

Effectively this solves the problem `y = G(\theta) = \bar{G}(\theta) + N(0,\Gamma)` , where we don't have access to `\bar{G}`, thus a sample of G already contains the correct variability and no regularization should be performed. As we provide only a sample `y` this will acheive a (naturally) biased result

To obtain consistency with the current CES framework, the sample of data for EKI and MCMC should be the same. 

## Solution?

Perhaps the simplest way to do this would be to have a flag `deterministic_forward_map=true`. 

- If true, the sample is perturbed at every iteration and ensemble member (as is traditional)
- If false, the sample is unperturbed.

**Comment by ilopezgp** [comment]
I believe this was resolved. Should we close @odunbar ?

**Comment by odunbar** [comment]
Yes we resolved this
