### ISSUE TITLE
JOSS Paper Review 2

### ISSUE THREAD

**Issue by ziyiyin97** [CliMA/EnsembleKalmanProcesses.jl#232]
My apologies for the late reviews https://github.com/openjournals/joss-reviews/issues/4869

Overall the package shows how to run derivative-free ensemble kalman process in Julia and entails quite clean documentation and examples. There are also a lot of useful references in the manuscript. A few comments:

1. In general how does this package compare to other Kalman-related packages? like Kalman.jl or other Julia/Python based packages?

Comments for the manuscript:
1. Line 30 "under certain conditions" -- probably need a reference.

In terms of the code/examples/docs:
1. The package claims that the prior distribution can be either from Julia Distributions or empirical/sample-based distributions. I would appreciate it if authors could provide an example related to sample-based distributions. (or point to reference)
2. Also appreciate an example w/ TOML I/O for a few iterations. (or point to reference) I assume these are both related to this module https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/main/src/UQParameters.jl

I hope these concerns can be easily addressed with more explanations or so.

**Comment by odunbar** [comment]
Hi @ziyiyin97 Thank you very much for your review. 

Proposed response:
_In paper.md_
- We are currently writing a state-of-field section for the other review, and where our code fits in, we shall include `Kalman.jl` in this.
- "under certain conditions" refers to the standard Kalman assumptions, we shall tighten up this statement.

_In the docs_
- We will add a docs for defining a sample-based distribution.
- We will add a docs tutorial for the TOML interface

_In the code_
- We will add a simple example that uses the TOML interface

We shall keep you updated! Thanks again

**Comment by ziyiyin97** [comment]
Sounds good!

**Comment by odunbar** [comment]
An update of where we are:
- PR #231 adds a state-of-field, and tightened Kalman assumptions (along with changes for the other review)
- PR #238 adds a replica of our simple sinusoid example, but uses the TOML and file-system interface between model and calibration tools. [Under Code Review]
- PR #240 adds some simple intuitive examples for creating prior distributions using "samples-based" distributions into the docs. [Under Code Review]
I'll ping you again when these are complete

**Comment by odunbar** [comment]
@ziyiyin97 I believe we have now addressed all the issues raised. 
- The changes to the paper are in [paper.pdf](https://github.com/CliMA/EnsembleKalmanProcesses.jl/files/10117338/paper.pdf)
- The new TOML example is found in [`examples/SinusoidInterface/`](https://github.com/CliMA/EnsembleKalmanProcesses.jl/tree/main/examples/SinusoidInterface)
- The docs for the TOML examples [here](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/examples/sinusoid_example_toml/#TOML-interface-for-fitting-parameters-of-a-sinusoid)
- The docs for the samples-example [here](https://clima.github.io/EnsembleKalmanProcesses.jl/dev/parameter_distributions/#samples-example)

**Comment by ziyiyin97** [comment]
Thanks for your quick update. The new TOML example in https://github.com/CliMA/EnsembleKalmanProcesses.jl/tree/main/examples/SinusoidInterface needs an updated version of EnsembleKalmanProcess otherwise `julia --project` will use the previous version of EnsembleKalmanProcess w/o `TOMLInterface` --i.e. `ERROR: UndefVarError: TOMLInterface not defined`. But everything else looks good to me and this issue can be fixed by burning a new release. Thanks again for your great work which enriches the Kalman community in Julia!
