### ISSUE TITLE
Returning constrained parameters

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#24]
Our current getter methods for EKP provide exactly the stored computational parameters. However in typical use with the G model requiring constrained parameters, it would be nice to have a getter function for this (otherwise one needs to apply it separately)

i.e for some `ekp::EnsembleKalmanProcess` object, and a created `prior::ParameterDistribution`  currently one applies
```julia 
computational_params = get_u_final(ekp)
physical_params = transform_unconstrained_to_constrained(prior,computational_params)
model_outputs = run_model_ensemble(physical_params)
```
## Solution options
We wish to apply the transformation internally. 

We could add new getters `get_u_constrained` and `get_u_constrained_final`. 

Or we could have a flag to `return_constrained` in the current getter

**Comment by ilopezgp** [comment]
Should it be

`physical_params = transform_unconstrained_to_constrained(prior,computational_params)` instead?

**Comment by odunbar** [comment]
corrected!

**Comment by odunbar** [comment]
Note also, when creating the `create_initial_ensemble` this appears to also be done in the unconstrained space.
