### ISSUE TITLE
Should be passing an RNG here, not just a seed

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#260]
https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/3e7494ee0f32db1ba2f7160e8c37bdceed34b2d1/src/EnsembleKalmanProcess.jl#L354

Just noticed that we pass in a seed here, this should be passing around an `rng::AbstractRNG` so users can use more stable options than `Random.seed!()`. 

In particular we should be writing functions that take in 
```function f(..., rng::RNG) where {RNG <: AbstractRNG}``` 
Or have a keyword with default 
```function f(..., rng = Random.default_rng())``` 

and the `rng` should be stored in the ekp object.

This will make randomness far more traceable in our code.

**Comment by costachris** [comment]
Will be addressed in #281
