### ISSUE TITLE
constrained_gaussian freezes

### ISSUE THREAD

**Issue by sdwfrost** [CliMA/EnsembleKalmanProcesses.jl#261]
The following code runs, but freezes - I suspect this is due to the choice of parameters, but no warning/error is thrown.

```julia
using EnsembleKalmanProcesses
using EnsembleKalmanProcesses.ParameterDistributions
constrained_gaussian("gamma", 0.5, 0.5, 0.0, 1.0)
```

**Comment by odunbar** [comment]
Thanks for pointing this out! Indeed, this is trying to create a bounded distribution within `[0,1]` but with mean of 0.5 and a standard deviation of 0.5. which hits the boundary.

For more outlandish values e.g. `constrained_gaussian("gamma", 0.5, 0.8, 0.0, 1.0)` it seems like our failsafe kicks in with an error. 

But i guess for this one (and some nearby, it tries to solve it without success). 

### Quick solves:

- Using `constrained_gaussian("gamma", 0.5, 0.4, 0.0, 1.0)` Will put a lot of mass at the boundaries, (mu=1e-5, sig=4.06 c.f. the figure below)
-  `constrained_gaussian("gamma", 0.5, 0.3, 0.0, 1.0)`  Will create something close to uniform (mu=1e-5, sig=1.81 c.f. fig below)
![image](https://user-images.githubusercontent.com/47412152/225992076-e66cab10-d129-47c2-895d-5a23f6df400d.png)
[from wikipedia logitnormal page]

https://en.wikipedia.org/wiki/Logit-normal_distribution

### Actions
- [ ] I'll see if we can tighten up the error message tolerance 
- [ ] in future we can improve the numerical solver robustness.

**Comment by odunbar** [comment]
Closing, now tolerances are sorted, and warning message implemented if solver will struggle.

**Comment by odunbar** [comment]
PR #266
