### ISSUE TITLE
remove cat(X...) statements

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#274]
For convenience we often use `cat(X..., dims=p)` statements to concatenate vectors and matrices. During some profile I see these become terribly inefficient at even moderate problems. We should probably remove them. As an example"

```julia
X = [zeros(3,3) for i = 1:1000]

# option 1 
xx = cat(X...,dims=3)

# option 2
function squidge(X::AbstractVector) 
       xx = zeros(size(X[1],1),size(X[1],2),length(X))
       for i = 1:length(X)
           xx[:,:,i] = X[i]
       end
       return xx
end
xx = squidge(X)
```
option 1 gives e.g.: 
 `0.037136 seconds (10.01 k allocations: 13.965 MiB)`
option 2 gives e.g.:
`0.000088 seconds (2 allocations: 70.375 KiB)`

## Action
Replace `cat(X...,dims=p)` with the appropriate loops.

**Comment by haakon-e** [comment]
Alternative with julia base functions ([ref](https://discourse.julialang.org/t/turn-vector-of-matrices-into-3d-array/69777/7?u=haakon)):
```julia
function squidge2(x)
    B = reduce(hcat, x);
    sz = size(X[1])
    C = reshape(B, sz[1], sz[2], :);
end
```
Gets: `0.000073 seconds (6 allocations: 70.516 KiB)`
