### ISSUE TITLE
License copyright text not filled out

### ISSUE THREAD

**Issue by JimCircadian** [CliMA/EnsembleKalmanProcesses.jl#276]
Hello

I'm deriving a [workflow](https://github.com/JimCircadian/KalmanEnsembling) using my [ensembler tool](https://github.com/jimCircadian/model-ensembler) for HPC ensembling of the examples and noticed your license text in `LICENSE` is not filled out (I'm including it to acknowledge the source of the example!) If you can fill it out, I'll re-add your license for proper attribution!!! 😄 

```
Copyright [yyyy] [name of copyright owner]
```

**Comment by odunbar** [comment]
Hi @JimCircadian Thanks for bringing this to our attention! I've just created a PR for this, and merge it in soon, likely with a 1.0.1 version number.

Also I'd like to thank you, both for your interest in our package, and for developing tools to aid with ensemble HPC. I think it's an often overlooked, yet important responsibility for our community to ease users into the paradigm shift towards ensemble computation! Thanks for taking this on!

**Comment by odunbar** [comment]
Addendum - Further updates from the our team indicates that we follow the [procedure as here](https://www.linkedin.com/pulse/how-apply-apache-20-license-your-open-source-software-vladim%C3%ADr-gorej/?trk=pulse-article_more-articles_related-content-card) and used in e.g., [ClimaCore.jl](https://github.com/CliMA/ClimaCore.jl).

This has a LICENSE file copied verbatim [unfilled], and a NOTICE file with the filled details, I shall do this now!
