### ISSUE TITLE
DocumenterFlavor not defined

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#43]
Trying to compile docs offline (and using the new installation instructions) gives me this error 
```
>julia --project=docs docs/make.jl 
ERROR: LoadError: UndefVarError: DocumenterFlavor not defined
...
in expression starting at /home/odunbar/Dropbox/Caltech/CESjl/EnsembleKalmanProcesses.jl/docs/make.jl:22
```

**Comment by navidcy** [comment]
Yeap. I fixed this in #41. :)

**Comment by odunbar** [comment]
My mistake! was on the wrong branch!

**Comment by navidcy** [comment]
https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/9e4963d085fb14349ecf6ff281cd8f9eff348c14/docs/make.jl#L24

**Comment by navidcy** [comment]
Oh, I see. No prob!

**Comment by navidcy** [comment]
So is this still outstanding?

**Comment by odunbar** [comment]
I am on your `ncc/literate-...` branch and that is where i get the error compiling the docs locally

**Comment by navidcy** [comment]
Try deleting `docs/Manifest.toml` and then re-instantiating following instructions here: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'

(Most probably you have installed an older version of Literate.jl before the `flavor` kwarg was implemented?

**Comment by odunbar** [comment]
Will do!

**Comment by navidcy** [comment]
Github actions Docs [builts OK](https://github.com/CliMA/EnsembleKalmanProcesses.jl/runs/3415980109?check_suite_focus=true) and preview is pushed here: https://clima.github.io/EnsembleKalmanProcesses.jl/previews/PR41/literated/loss_minimization/

**Comment by odunbar** [comment]
OK deleting the Manifest seems to have done the trick. Cheers! I'll close this
