### ISSUE TITLE
Ensemble Kalman Sampler in docs doesn't match the implementation

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#50]
We talk about the [vanilla EKS implementation](https://epubs.siam.org/doi/abs/10.1137/19M1251655), however in implementation we use a linear-corrected version proposed through the paper chain of [here](https://arxiv.org/abs/1908.10890), and subsequently [here ](https://epubs.siam.org/doi/abs/10.1137/19M1304891). This is shown to have better numerical and analytical properties than the original proposed EKS.

The authors of the final paper I believe give the correction of the method a new name too. We should take care with how it is presented. Perhaps I can work with @agarbuno with the documentation for this

**Comment by odunbar** [comment]
We should also mention the adaptive timestepping used.

**Comment by agarbuno** [comment]
Yep, so we basically need to incorporate: 
- [ ] Wording and references. 
- [ ] Time-stepping scheme and references.
