### ISSUE TITLE
Functionality to plot prior pdf (in constrained and unconstrained space)

### ISSUE THREAD

**Issue by bielim** [CliMA/EnsembleKalmanProcesses.jl#52]
**Proposal**
I think that users would appreciate the ability to plot the pdf of a `ParameterDistribution`, both in unconstrained an in constrained space. E.g., one could provide a function `plot_pdf(xarray::Array{<:Real,1}, pd::ParameterDistribution, constrained::Bool=false, kw...)` that takes a parameter distribution and plots either the pdf of the unconstrained distribution or that of the constrained distribution.

**Why?**
In practice, the choice of priors is probably one of the most difficult aspects of using `EnsembleKalmanProcesses.jl` as it requires one to understand the concept of transformations between constrained and unconstrained spaces, and also because most scientists working with a model really tend to think about parameter distributions in the constrained model space (rather than in the unconstrained space where the algorithm takes place), since that is what they have some physical insight or intuition about. So it would be nice for them to see what the pdf in unconstrained space gets mapped into when sending it into the constrained space.

Implementing plotting capability in a reasonably general way (including high dimensions, distributions from correlated samples etc.) requires a lot of thought. But even an implementation that is limited to simple cases could be useful.

**Comment by navidcy** [comment]
I agree. A functionality to streamline visualising that is needed. Or even just a functionality that is able to provide a tuple of arrays, e.g. `(parameter_values, pdf)` is enough! This way we won't need to include plotting packages as dependencies of EnsembleKalmanProcesses.jl.

Have a look at
https://clima.github.io/OceanTurbulenceParameterEstimation.jl/dev/literated/baroclinic_adjustment_perfect_model_calibration/#Free-parameters

Would something like that work?
