### ISSUE TITLE
Random seeds

### ISSUE THREAD

**Issue by odunbar** [CliMA/EnsembleKalmanProcesses.jl#55]
We add noise during various updates, for example when the forward map is deterministic it is used to stabilize the method. Some users may require fixing random seeds, we have done this during the initial ensemble construction,  but not yet for the update of the ensemble. for example in EKI
e.g. https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/4252146c019a133bc3ef5daeeb7e912371be38f0/src/EnsembleKalmanInversion.jl#L77
It would be nice to have the random seeding option
Coauthored with @trontrytel

**Comment by ilopezgp** [comment]
Closed by @tsj5 's PR #95 .
