### ISSUE TITLE
Should we be building the Docs with Julia v1.6.4?

### ISSUE THREAD

**Issue by navidcy** [CliMA/EnsembleKalmanProcesses.jl#79]
https://github.com/CliMA/EnsembleKalmanProcesses.jl/blob/f5eac9b77d503a598cb4655f4c07522ba986e317/.github/workflows/Docs.yml#L29

**Comment by odunbar** [comment]
I have no preference, or knowledge, of the Docs builder - would be happy if it was updated - perhaps yourself or @jakebolewski could resolve this? Thanks!

**Comment by jakebolewski** [comment]
1.5.4 -> 1.7.0
