### ISSUE TITLE
Simplify interface

### ISSUE THREAD

**Issue by charleskawczynski** [CliMA/EnsembleKalmanProcesses.jl#92]
One of the nice parts of Julia is that we can extend existing methods, for example, 

```julia
get_mean(d::Parameterized) = mean(d.distribution)
```
could simply extend the `StatsBase` `mean` method
```julia
import StatsBase
...
StatsBase.mean(d::Parameterized) = StatsBase.mean(d.distribution)
```
This can be applied to several methods (e.g., `get_mean`, `len`, `size` etc.)

**Comment by ilopezgp** [comment]
Let's go through these before release `0.2`, since some of these will be breaking changes.
