### ISSUE TITLE
Covariance matrix `obs_noise_cov` is restricted to `Array{FT, 2}`

### ISSUE THREAD

**Issue by glwagner** [CliMA/EnsembleKalmanProcesses.jl#99]
The type of `EnsembleKalmanProcess.obs_noise_cov` is restricted to `Array{FT, 2}`, which is inconvenient and prevents the use of common `LinearAlgebra` abstractions that represent arrays.

For example:

```julia
julia> using EnsembleKalmanProcesses, EnsembleKalmanProcesses.ParameterDistributions, LinearAlgebra, Distributions

julia> distribution = ParameterDistribution(Parameterized(Normal(0, 1)), no_constraint(), "");

julia> sample = sample_distribution(distribution, 1);

julia> obs_noise_cov = 0.1*I
UniformScaling{Float64}
0.1*I

julia> ekp = EnsembleKalmanProcess(sample, zeros(2), obs_noise_cov, Inversion())
ERROR: MethodError: no method matching EnsembleKalmanProcess(::Matrix{Float64}, ::Vector{Float64}, ::UniformScaling{Float64}, ::Inversion)
...
```

`0.1 * I` is a valid and efficient way to specify a covariance matrix. The code itself likely works as is, since key lines like

```julia
julia> noise = rand(MvNormal(zeros(2), 0.1 * I), 2)
2×2 Matrix{Float64}:
 0.0551659  0.720873
 0.057236   0.289555
```

are valid for a wide variety of matrix types. Thus probably the only change needed is to release `obs_noise_cov` from `Array{FT, 2}`.

For large observation vectors the need to convert objects like `UniformScaling` to `Array{FT, 2}` is a waste of memory:

```julia
julia> Matrix(0.1*I, 5, 5)
5×5 Matrix{Float64}:
 0.1  0.0  0.0  0.0  0.0
 0.0  0.1  0.0  0.0  0.0
 0.0  0.0  0.1  0.0  0.0
 0.0  0.0  0.0  0.1  0.0
 0.0  0.0  0.0  0.0  0.1
```

Another important matrix type is `Diagonal` representing a diagonal matrix.

cc @simonbyrne

**Comment by odunbar** [comment]
For sure, the creation of the package was done with types being used to restrict arguments (before i even knew about the difficulties with matrix != array{,2} != DiagonalMatrix type problems) 

I think for Covariance matrices, I am happy to take the broadest umbrella type that can have a dimension specified (i.e. must be 2D)?

**Comment by glwagner** [comment]
You want to use a variable concrete type:

```julia
obs_noise_cov::M
```

The type union `Union{UniformScaling, AbstractMatrix}` might cover enough cases.

For user-facing functions / constructors, you should probably catch invalid types and throw a useful error rather than relying on `MethodError`:

```julia
obs_noise_cov isa Union{UniformScaling, AbstractMatrix} ||
    throw(ArgumentError(string(summary(obs_noise_cov), " obs_noise_cov is not supported. Use UniformScaling or AbstractMatrix"))
```

or something like that.

I think its better to add input validation later, once you have some experience working with the code and a good working understanding of the range of valid types that work (and common user mistakes).
